# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e28b5b80c7475fdb4f912bfe7b09ab6f6617389d9937a7ab6bd12951beb4a6788900157025ff0ec85a99e91fe91b6581276cae656ea187a30fa52e90621de3e8

test:
  secret_key_base: de73011e4169ef945cce108280d381fc52f9c73ec877300af022b0ff68846fda32f78df2b810f7c6c6f2e6389152a088e74ecdb6855124fe6be90059a5d33ae5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
